sudo: false
language: node_js
matrix:
  include:
    - node_js: '6'
      os: linux
    - node_js: '5'
      os: linux
    - node_js: '4'
      os: linux
    - node_js: '6'
      os: osx
    - node_js: '5'
      os: osx
