sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.9
      - libssl-dev
      - libjpeg62-dev
      - libgif-dev
      - pkg-config

language: node_js
matrix:
  include:
    - env: CXX=g++-4.9
      node_js: '6'
      os: linux
    - env: CXX=g++-4.9
      node_js: '5'
      os: linux
    - env: CXX=g++-4.9
      node_js: '4'
      os: linux
    - env: CXX=g++-4.9
      node_js: '6'
      os: osx
    - env: CXX=g++-4.9
      node_js: '5'
      os: osx
    - env: CXX=g++-4.9
      node_js: '4'
      os: osx
